[package]
name = "csr-with-tailwind"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.6", features = ["csr"] }
leptos-use = "0.10.4"
leptix_primitives = { path = "../../crates/primitives" }
